/**
 * Builds the static frontend for hosts that cannot run Node (GitHub Pages).
 *
 * The full app is a server app. Rather than compromise it, this prepares an
 * isolated copy in .static-build/ with the server-only surfaces removed, runs
 * `next build` with output: 'export' there, and copies the resulting HTML to
 * ./out.
 *
 * Content is NOT lost: pages are statically generated, which means they read
 * from SQLite at BUILD time and bake the current CMS content into the HTML.
 * Editing content afterwards therefore requires a rebuild — which is precisely
 * the trade-off static hosting imposes, and why the Node deployment exists.
 *
 * Removed from the static copy:
 *   src/app/api      route handlers cannot be exported
 *   src/app/admin    needs sessions, cookies and a live database
 *   src/app/uploads  runtime file streaming
 *
 * Usage: npm run build:static
 */
import { cp, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const WORK = path.join(ROOT, '.static-build');
const OUT = path.join(ROOT, 'out');

/** Directories excluded when mirroring the project into the work area. */
const SKIP = new Set([
  'node_modules', '.next', '.git', 'out', '.static-build', 'data', '.assets-src',
]);

async function mirror(from: string, to: string) {
  await mkdir(to, { recursive: true });
  for (const entry of await readdir(from, { withFileTypes: true })) {
    if (SKIP.has(entry.name)) continue;
    const src = path.join(from, entry.name);
    const dst = path.join(to, entry.name);
    if (entry.isDirectory()) await mirror(src, dst);
    else await cp(src, dst);
  }
}

/** Strips `export const dynamic = 'force-dynamic'` so pages can prerender. */
async function makePagesStatic(dir: string): Promise<number> {
  let patched = 0;
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      patched += await makePagesStatic(full);
      continue;
    }
    if (!/\.tsx?$/.test(entry.name)) continue;

    const source = await readFile(full, 'utf8');
    if (!source.includes("dynamic = 'force-dynamic'")) continue;

    const next = source.replace(
      /\/\*\*[\s\S]*?\*\/\s*export const dynamic = 'force-dynamic';\n?|export const dynamic = 'force-dynamic';\n?/g,
      '',
    );
    await writeFile(full, next);
    patched += 1;
  }
  return patched;
}

/** Dynamic routes need their params enumerated up front for an export. */
const STATIC_PARAMS: Record<string, string> = {
  'src/app/(site)/studios/[slug]/page.tsx': `
export function generateStaticParams() {
  return getStudioSlugs().map((slug) => ({ slug }));
}
`,
  'src/app/(site)/services/[slug]/page.tsx': `
export function generateStaticParams() {
  return getServiceSlugs().map((slug) => ({ slug }));
}
`,
};

async function addStaticParams() {
  for (const [rel, snippet] of Object.entries(STATIC_PARAMS)) {
    const file = path.join(WORK, rel);
    let source = await readFile(file, 'utf8');
    if (source.includes('generateStaticParams')) continue;

    // Ensure the slug helper is imported.
    const helper = rel.includes('studios') ? 'getStudioSlugs' : 'getServiceSlugs';
    if (!source.includes(helper)) {
      source = source.replace(
        /(import \{[^}]*)(\} from '@\/lib\/db\/queries';)/,
        `$1, ${helper}$2`,
      );
    }
    // Insert after the import block.
    const lastImport = source.lastIndexOf("';\n", source.indexOf('export'));
    const at = source.indexOf('\n', lastImport) + 1;
    source = source.slice(0, at) + snippet + source.slice(at);
    await writeFile(file, source);
  }
}

async function writeStaticConfig(basePath: string) {
  const config = `import type { NextConfig } from 'next';

/**
 * Static-export configuration. Generated by scripts/build-static.ts —
 * do not edit by hand.
 *
 * Security headers are omitted deliberately: a static host serves them from
 * its own configuration, and next.config headers() has no effect on an export.
 * Configure equivalents at the host or CDN.
 */
const nextConfig: NextConfig = {
  output: 'export',
  reactStrictMode: true,
  poweredByHeader: false,
${basePath ? `  basePath: '${basePath}',\n  assetPrefix: '${basePath}',\n` : ''}  // Emits every route as a directory with index.html, which is how static
  // hosts resolve nested paths without a rewrite rule.
  trailingSlash: true,
  images: {
    // No server means no on-demand optimisation. Our images are already
    // pre-generated as AVIF/WebP at three widths, so nothing is lost.
    unoptimized: true,
  },
};

export default nextConfig;
`;
  await writeFile(path.join(WORK, 'next.config.ts'), config);
}

/** Rebase public media in HTML, flight data and client chunks for project Pages.
 * Next handles Link and _next paths, but plain picture/srcSet URLs are ours.
 * Only known public asset paths are touched; HTML closing tags stay intact.
 */
async function rebasePublicAssets(dir: string, basePath: string) {
  if (!basePath) return;
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const file = path.join(dir, entry.name);
    if (entry.isDirectory()) { await rebasePublicAssets(file, basePath); continue; }
    if (!/\.(html|txt|js|css|json|xml)$/.test(entry.name)) continue;
    const source = await readFile(file, 'utf8');
    const result = source.replace(
      /(?<![a-zA-Z0-9_/.:-])\/(media\/|logo(?:-dark|-light)?\.svg|og-image\.png|favicon\.(?:svg|ico)|apple-icon\.png)/g,
      `${basePath}/$1`,
    );
    if (result !== source) await writeFile(file, result);
  }
}

async function main() {
  // A project repo is served from /<repo>, a user/org site from the root.
  const basePath = process.env.LM_BASE_PATH ?? '';

  console.log('Preparing static export workspace…');
  await rm(WORK, { recursive: true, force: true });
  await mirror(ROOT, WORK);

  // Remove everything that requires a server.
  for (const dir of ['src/app/api', 'src/app/admin', 'src/app/uploads']) {
    await rm(path.join(WORK, dir), { recursive: true, force: true });
    console.log(`  removed ${dir}`);
  }

  const patched = await makePagesStatic(path.join(WORK, 'src/app'));
  console.log(`  made ${patched} page(s) statically renderable`);

  await addStaticParams();
  console.log('  added generateStaticParams to dynamic routes');

  // robots.ts and sitemap.ts are route handlers, not pages: an export requires
  // them to opt in explicitly rather than merely not being dynamic.
  for (const rel of ['src/app/robots.ts', 'src/app/sitemap.ts']) {
    const file = path.join(WORK, rel);
    if (!existsSync(file)) continue;
    const source = await readFile(file, 'utf8');
    if (source.includes("dynamic = 'force-static'")) continue;
    await writeFile(file, `export const dynamic = 'force-static';\n\n${source}`);
  }
  console.log('  marked robots and sitemap as force-static');

  await writeStaticConfig(basePath);
  console.log(`  wrote export config${basePath ? ` (basePath ${basePath})` : ''}`);

  // The database must exist — static generation reads content from it.
  const dataDir = process.env.LM_DATA_DIR ?? path.join(ROOT, 'data');
  if (!existsSync(path.join(dataDir, 'live-miracle.db'))) {
    throw new Error(
      `No database at ${dataDir}. Run \`npm run db:seed\` before building the static site — ` +
        'static generation reads all page content from it.',
    );
  }

  console.log('\nBuilding…\n');
  const build = spawnSync('npx', ['next', 'build'], {
    cwd: WORK,
    stdio: 'inherit',
    env: {
      ...process.env,
      NODE_ENV: 'production',
      NEXT_PUBLIC_LM_STATIC: '1',
      NEXT_PUBLIC_LM_BASE_PATH: basePath,
      // Absolute path so the copied project reads the real database.
      LM_DATA_DIR: dataDir,
      LM_APP_SECRET: process.env.LM_APP_SECRET ?? 'static-build-placeholder-secret-000000000000',
    },
  });
  if (build.status !== 0) throw new Error('next build failed');

  await rm(OUT, { recursive: true, force: true });
  await cp(path.join(WORK, 'out'), OUT, { recursive: true });
  await rebasePublicAssets(OUT, basePath);

  // Pages runs Jekyll by default, which strips files and folders beginning
  // with an underscore — including Next's _next asset directory.
  await writeFile(path.join(OUT, '.nojekyll'), '');

  const pages = (await readdir(OUT, { withFileTypes: true }))
    .filter((e) => e.isDirectory() && e.name !== '_next')
    .map((e) => e.name);

  console.log(`\nStatic site written to out/`);
  console.log(`  routes: ${pages.join(', ')}`);
  console.log('  .nojekyll written (stops Pages stripping /_next)');
}

main().catch((err) => {
  console.error(`\n${err.message}`);
  process.exit(1);
});
