import { ApiError, withAdminApi } from '@/lib/auth/guard';
import { deleteStored } from '@/lib/admin/media-store';
import { getDb, now } from '@/lib/db/client';
import { fieldErrors, mediaMetaSchema } from '@/lib/validation/schemas';
import { parseIdFromUrl } from '@/lib/admin/resource';

export const dynamic = 'force-dynamic';

/** Update alt text and caption. */
export const PATCH = withAdminApi(
  async ({ req, audit }) => {
    const id = parseIdFromUrl(req);
    const body = await req.json().catch(() => null);
    const parsed = mediaMetaSchema.safeParse(body);
    if (!parsed.success) {
      throw new ApiError(400, 'Invalid media metadata.', 'invalid', fieldErrors(parsed.error));
    }

    const db = getDb();
    if (!db.prepare('SELECT id FROM media WHERE id = ?').get(id)) {
      throw new ApiError(404, 'Media not found.', 'not_found');
    }

    db.prepare('UPDATE media SET alt = ?, caption = ?, updated_at = ? WHERE id = ?')
      .run(parsed.data.alt, parsed.data.caption, now(), id);

    audit('media.update', 'media', id);
    return { id };
  },
  { permission: 'media.write' },
);

/**
 * Deletes a media item and its files.
 *
 * Assets shipped with the build (is_managed = 1) are refused: they are
 * regenerated by the build pipeline, so deleting the row would leave the studio
 * records pointing at nothing until the next deploy. Their metadata stays
 * editable instead.
 */
export const DELETE = withAdminApi(
  async ({ req, audit }) => {
    const id = parseIdFromUrl(req);
    const db = getDb();

    const media = db
      .prepare('SELECT id, storage_key, is_managed, kind FROM media WHERE id = ?')
      .get(id) as { id: number; storage_key: string; is_managed: number; kind: string } | undefined;
    if (!media) throw new ApiError(404, 'Media not found.', 'not_found');

    if (media.is_managed === 1) {
      throw new ApiError(
        409,
        'This asset ships with the build and cannot be deleted here. Replace the source file instead.',
        'managed_asset',
      );
    }

    // Report what will break before removing it — foreign keys are ON DELETE
    // SET NULL, so nothing cascades, but the editor should know.
    const usage = {
      studioImages: (db.prepare('SELECT COUNT(*) c FROM studio_images WHERE media_id = ?').get(id) as { c: number }).c,
      studioVideos: (db.prepare('SELECT COUNT(*) c FROM studio_videos WHERE media_id = ? OR poster_media_id = ?').get(id, id) as { c: number }).c,
      gallery: (db.prepare('SELECT COUNT(*) c FROM gallery WHERE media_id = ?').get(id) as { c: number }).c,
      timeline: (db.prepare('SELECT COUNT(*) c FROM timeline_events WHERE media_id = ?').get(id) as { c: number }).c,
    };

    db.prepare('DELETE FROM media WHERE id = ?').run(id);
    await deleteStored(media.storage_key);

    audit('media.delete', 'media', id, { storageKey: media.storage_key, usage });
    return { deleted: id, detachedFrom: usage };
  },
  { permission: 'media.delete' },
);
